Repository pawelsobkowski/travello, pull requests merged in 2021-02, with the labels that each got.

#2 Feat zawolanski
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/index.css
  src/index.js
  src/logo.svg
  src/templates/Header/index.js
  src/templates/Main/index.js
  src/theme/GlobalStyles.js
  src/theme/theme.js
  src/views/Dashboard/index.js
  src/views/Details/index.js
  src/views/Home/index.js
  src/views/Profile/index.js
  src/views/Root/index.js
  src/views/Search/index.js
  src/views/Signin/index.js
  src/views/Signup/index.js
Labels: enhancement

#3 Feat zawolanski
  .eslintrc.js
  package-lock.json
  package.json
  public/index.html
  src/assets/icon/arrow_right.svg
  src/assets/icon/avatar.svg
  src/assets/icon/bookmark.svg
  src/assets/icon/chevron_down.svg
  src/assets/icon/close.svg
  src/assets/icon/compass.svg
  src/assets/icon/google.svg
  src/assets/icon/logout.svg
  src/assets/icon/search.svg
  src/assets/icon/user.svg
  src/components/ButtonWIthIcon/index.js
  src/components/ButtonWIthIcon/styles.js
  src/components/IconButton/index.js
  src/components/IconButton/styles.js
  src/templates/Header/index.js
  src/templates/Header/styles.js
  src/theme/GlobalStyles.js
  src/theme/theme.js
  src/views/Home/index.js
  src/views/Home/styles.js
  src/views/Root/index.js
Labels: enhancement

#4 fix routes overwrites
  src/views/Root/index.js
Labels: bug, invalid

#5 Create animations at home page
  package-lock.json
  package.json
  src/assets/icon/chevron_left.svg
  src/assets/icon/chevron_right.svg
  src/components/IconButton/index.js
  src/components/SliderCard/index.js
  src/components/SliderCard/styles.js
  src/theme/GlobalStyles.js
  src/variants/home.js
  src/views/Home/index.js
  src/views/Home/styles.js
Labels: bug, enhancement, invalid

#6 Initial bootstrap for dashboard for mobile
  src/components/Card/index.js
  src/components/Card/style.js
  src/components/CardSlider/index.js
  src/components/CardSlider/style.js
  src/templates/Header/styles.js
  src/theme/GlobalStyles.js
  src/theme/theme.js
  src/views/Dashboard/index.js
  src/views/Dashboard/style.js
Labels: enhancement
